"""initial schema

Revision ID: 118247dd7b63
Revises: 
Create Date: 2026-03-24 21:12:32.125862
"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '118247dd7b63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('projected_crs', sa.String(length=20), nullable=False),
    sa.Column('total_street_segments', sa.Integer(), nullable=False),
    sa.Column('total_street_length_m', sa.Float(), nullable=False),
    sa.Column('osm_data_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strava_athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('strava_scope', sa.String(length=100), nullable=False),
    sa.Column('home_city_id', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_access_token_hash'), 'users', ['access_token_hash'], unique=True)
    op.create_index(op.f('ix_users_strava_athlete_id'), 'users', ['strava_athlete_id'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=False),
    sa.Column('summary_polyline', sa.Text(), nullable=True),
    sa.Column('detailed_polyline', sa.Text(), nullable=True),
    sa.Column('gps_trace', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('has_gps', sa.Boolean(), nullable=False),
    sa.Column('is_on_street', sa.Boolean(), nullable=False),
    sa.Column('import_status', sa.String(length=20), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_strava_activity_id'), 'activities', ['strava_activity_id'], unique=True)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_index('ix_activity_user_sport_type', 'activities', ['user_id', 'sport_type'], unique=False)
    op.create_index('ix_activity_user_start_date', 'activities', ['user_id', 'start_date'], unique=False)
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('total_street_segments', sa.Integer(), nullable=False),
    sa.Column('total_street_length_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'name', name='uq_neighborhood_city_name')
    )
    op.create_index(op.f('ix_neighborhoods_city_id'), 'neighborhoods', ['city_id'], unique=False)
    op.create_table('coverage_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('coverage_percentage', sa.Float(), nullable=False),
    sa.Column('total_streets_traveled', sa.Integer(), nullable=False),
    sa.Column('total_streets', sa.Integer(), nullable=False),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('milestone_label', sa.String(length=50), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'city_id', 'neighborhood_id', 'snapshot_date', name='uq_snapshot')
    )
    op.create_index(op.f('ix_coverage_snapshots_city_id'), 'coverage_snapshots', ['city_id'], unique=False)
    op.create_index(op.f('ix_coverage_snapshots_user_id'), 'coverage_snapshots', ['user_id'], unique=False)
    op.create_table('route_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('start_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('requested_distance_meters', sa.Float(), nullable=False),
    sa.Column('untraveled_distance_meters', sa.Float(), nullable=False),
    sa.Column('untraveled_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_suggestions_user_id'), 'route_suggestions', ['user_id'], unique=False)
    op.create_table('street_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('osm_way_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_node_start', sa.BigInteger(), nullable=False),
    sa.Column('osm_node_end', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('highway_type', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_street_segment_city_neighborhood', 'street_segments', ['city_id', 'neighborhood_id'], unique=False)
    op.create_index(op.f('ix_street_segments_city_id'), 'street_segments', ['city_id'], unique=False)
    op.create_index(op.f('ix_street_segments_neighborhood_id'), 'street_segments', ['neighborhood_id'], unique=False)
    op.create_table('route_suggestion_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_suggestion_id', sa.Integer(), nullable=False),
    sa.Column('street_segment_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_untraveled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['route_suggestion_id'], ['route_suggestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['street_segment_id'], ['street_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_suggestion_segments_route_suggestion_id'), 'route_suggestion_segments', ['route_suggestion_id'], unique=False)
    op.create_table('user_street_coverages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street_segment_id', sa.Integer(), nullable=False),
    sa.Column('coverage_ratio', sa.Float(), nullable=False),
    sa.Column('is_traveled', sa.Boolean(), nullable=False),
    sa.Column('first_traveled_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['street_segment_id'], ['street_segments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'street_segment_id', name='uq_user_street')
    )
    op.create_index(op.f('ix_user_street_coverages_street_segment_id'), 'user_street_coverages', ['street_segment_id'], unique=False)
    op.create_index(op.f('ix_user_street_coverages_user_id'), 'user_street_coverages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_street_coverages_user_id'), table_name='user_street_coverages')
    op.drop_index(op.f('ix_user_street_coverages_street_segment_id'), table_name='user_street_coverages')
    op.drop_table('user_street_coverages')
    op.drop_index(op.f('ix_route_suggestion_segments_route_suggestion_id'), table_name='route_suggestion_segments')
    op.drop_table('route_suggestion_segments')
    op.drop_index(op.f('ix_street_segments_neighborhood_id'), table_name='street_segments')
    op.drop_index(op.f('ix_street_segments_city_id'), table_name='street_segments')
    op.drop_index('ix_street_segment_city_neighborhood', table_name='street_segments')
    op.drop_table('street_segments')
    op.drop_index(op.f('ix_route_suggestions_user_id'), table_name='route_suggestions')
    op.drop_table('route_suggestions')
    op.drop_index(op.f('ix_coverage_snapshots_user_id'), table_name='coverage_snapshots')
    op.drop_index(op.f('ix_coverage_snapshots_city_id'), table_name='coverage_snapshots')
    op.drop_table('coverage_snapshots')
    op.drop_index(op.f('ix_neighborhoods_city_id'), table_name='neighborhoods')
    op.drop_table('neighborhoods')
    op.drop_index('ix_activity_user_start_date', table_name='activities')
    op.drop_index('ix_activity_user_sport_type', table_name='activities')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_strava_activity_id'), table_name='activities')
    op.drop_index('idx_activities_gps_trace', table_name='activities', postgresql_using='gist')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_strava_athlete_id'), table_name='users')
    op.drop_index(op.f('ix_users_access_token_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_cities_boundary', table_name='cities', postgresql_using='gist')
    op.drop_table('cities')
    # ### end Alembic commands ###
