"""add_start_points_plans_goals

Revision ID: 69ccd5bab23b
Revises: 118247dd7b63
Create Date: 2026-03-28 13:30:45.186619
"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '69ccd5bab23b'
down_revision: Union[str, None] = '118247dd7b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('target_coverage_pct', sa.Float(), nullable=False),
    sa.Column('current_coverage_pct', sa.Float(), nullable=False),
    sa.Column('preferred_route_distance_m', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_goals_user_id'), 'coverage_goals', ['user_id'], unique=False)
    op.create_table('user_start_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_start_points_user_id'), 'user_start_points', ['user_id'], unique=False)
    op.create_table('coverage_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preferred_route_distance_m', sa.Float(), nullable=False),
    sa.Column('initial_coverage_pct', sa.Float(), nullable=False),
    sa.Column('target_coverage_pct', sa.Float(), nullable=False),
    sa.Column('total_routes', sa.Integer(), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['coverage_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_plans_user_id'), 'coverage_plans', ['user_id'], unique=False)
    op.create_table('coverage_plan_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('route_suggestion_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('streets_targeted', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['coverage_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_suggestion_id'], ['route_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_plan_routes_plan_id'), 'coverage_plan_routes', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_plan_routes_plan_id'), table_name='coverage_plan_routes')
    op.drop_table('coverage_plan_routes')
    op.drop_index(op.f('ix_coverage_plans_user_id'), table_name='coverage_plans')
    op.drop_table('coverage_plans')
    op.drop_index(op.f('ix_user_start_points_user_id'), table_name='user_start_points')
    op.drop_table('user_start_points')
    op.drop_index(op.f('ix_coverage_goals_user_id'), table_name='coverage_goals')
    op.drop_table('coverage_goals')
    # ### end Alembic commands ###
